// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

package function

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{3}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type IsAuthenticatedRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthenticatedRequest) Reset()         { *m = IsAuthenticatedRequest{} }
func (m *IsAuthenticatedRequest) String() string { return proto.CompactTextString(m) }
func (*IsAuthenticatedRequest) ProtoMessage()    {}
func (*IsAuthenticatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{4}
}
func (m *IsAuthenticatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthenticatedRequest.Unmarshal(m, b)
}
func (m *IsAuthenticatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthenticatedRequest.Marshal(b, m, deterministic)
}
func (dst *IsAuthenticatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthenticatedRequest.Merge(dst, src)
}
func (m *IsAuthenticatedRequest) XXX_Size() int {
	return xxx_messageInfo_IsAuthenticatedRequest.Size(m)
}
func (m *IsAuthenticatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthenticatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthenticatedRequest proto.InternalMessageInfo

func (m *IsAuthenticatedRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IsAuthenticatedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type IsAuthenticatedResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthenticatedResponse) Reset()         { *m = IsAuthenticatedResponse{} }
func (m *IsAuthenticatedResponse) String() string { return proto.CompactTextString(m) }
func (*IsAuthenticatedResponse) ProtoMessage()    {}
func (*IsAuthenticatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{5}
}
func (m *IsAuthenticatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthenticatedResponse.Unmarshal(m, b)
}
func (m *IsAuthenticatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthenticatedResponse.Marshal(b, m, deterministic)
}
func (dst *IsAuthenticatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthenticatedResponse.Merge(dst, src)
}
func (m *IsAuthenticatedResponse) XXX_Size() int {
	return xxx_messageInfo_IsAuthenticatedResponse.Size(m)
}
func (m *IsAuthenticatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthenticatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthenticatedResponse proto.InternalMessageInfo

func (m *IsAuthenticatedResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

type CreateConversationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationName     string   `protobuf:"bytes,3,opt,name=conversation_name,json=conversationName,proto3" json:"conversation_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationRequest) Reset()         { *m = CreateConversationRequest{} }
func (m *CreateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConversationRequest) ProtoMessage()    {}
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{6}
}
func (m *CreateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationRequest.Unmarshal(m, b)
}
func (m *CreateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationRequest.Merge(dst, src)
}
func (m *CreateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConversationRequest.Size(m)
}
func (m *CreateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationRequest proto.InternalMessageInfo

func (m *CreateConversationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateConversationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateConversationRequest) GetConversationName() string {
	if m != nil {
		return m.ConversationName
	}
	return ""
}

type CreateConversationResponse struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationResponse) Reset()         { *m = CreateConversationResponse{} }
func (m *CreateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResponse) ProtoMessage()    {}
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{7}
}
func (m *CreateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResponse.Unmarshal(m, b)
}
func (m *CreateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResponse.Marshal(b, m, deterministic)
}
func (dst *CreateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResponse.Merge(dst, src)
}
func (m *CreateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResponse.Size(m)
}
func (m *CreateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResponse proto.InternalMessageInfo

func (m *CreateConversationResponse) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type JoinConversationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationId       string   `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinConversationRequest) Reset()         { *m = JoinConversationRequest{} }
func (m *JoinConversationRequest) String() string { return proto.CompactTextString(m) }
func (*JoinConversationRequest) ProtoMessage()    {}
func (*JoinConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{8}
}
func (m *JoinConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinConversationRequest.Unmarshal(m, b)
}
func (m *JoinConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinConversationRequest.Marshal(b, m, deterministic)
}
func (dst *JoinConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinConversationRequest.Merge(dst, src)
}
func (m *JoinConversationRequest) XXX_Size() int {
	return xxx_messageInfo_JoinConversationRequest.Size(m)
}
func (m *JoinConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinConversationRequest proto.InternalMessageInfo

func (m *JoinConversationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *JoinConversationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinConversationRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type JoinConversationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinConversationResponse) Reset()         { *m = JoinConversationResponse{} }
func (m *JoinConversationResponse) String() string { return proto.CompactTextString(m) }
func (*JoinConversationResponse) ProtoMessage()    {}
func (*JoinConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{9}
}
func (m *JoinConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinConversationResponse.Unmarshal(m, b)
}
func (m *JoinConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinConversationResponse.Marshal(b, m, deterministic)
}
func (dst *JoinConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinConversationResponse.Merge(dst, src)
}
func (m *JoinConversationResponse) XXX_Size() int {
	return xxx_messageInfo_JoinConversationResponse.Size(m)
}
func (m *JoinConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinConversationResponse proto.InternalMessageInfo

type IsConversationMemberRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationId       string   `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsConversationMemberRequest) Reset()         { *m = IsConversationMemberRequest{} }
func (m *IsConversationMemberRequest) String() string { return proto.CompactTextString(m) }
func (*IsConversationMemberRequest) ProtoMessage()    {}
func (*IsConversationMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{10}
}
func (m *IsConversationMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsConversationMemberRequest.Unmarshal(m, b)
}
func (m *IsConversationMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsConversationMemberRequest.Marshal(b, m, deterministic)
}
func (dst *IsConversationMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsConversationMemberRequest.Merge(dst, src)
}
func (m *IsConversationMemberRequest) XXX_Size() int {
	return xxx_messageInfo_IsConversationMemberRequest.Size(m)
}
func (m *IsConversationMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsConversationMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsConversationMemberRequest proto.InternalMessageInfo

func (m *IsConversationMemberRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *IsConversationMemberRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IsConversationMemberRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type IsConversationMemberResponse struct {
	Member               bool     `protobuf:"varint,1,opt,name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsConversationMemberResponse) Reset()         { *m = IsConversationMemberResponse{} }
func (m *IsConversationMemberResponse) String() string { return proto.CompactTextString(m) }
func (*IsConversationMemberResponse) ProtoMessage()    {}
func (*IsConversationMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{11}
}
func (m *IsConversationMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsConversationMemberResponse.Unmarshal(m, b)
}
func (m *IsConversationMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsConversationMemberResponse.Marshal(b, m, deterministic)
}
func (dst *IsConversationMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsConversationMemberResponse.Merge(dst, src)
}
func (m *IsConversationMemberResponse) XXX_Size() int {
	return xxx_messageInfo_IsConversationMemberResponse.Size(m)
}
func (m *IsConversationMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsConversationMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsConversationMemberResponse proto.InternalMessageInfo

func (m *IsConversationMemberResponse) GetMember() bool {
	if m != nil {
		return m.Member
	}
	return false
}

type SendMessageRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationId       string   `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{12}
}
func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (dst *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(dst, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SendMessageRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SendMessageRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *SendMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{13}
}
func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (dst *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(dst, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

type ReadMessagesRequest struct {
	UserId         string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token          string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationId string `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// RFC3339 UTC
	FromTimestamp        string   `protobuf:"bytes,4,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`
	ToTimestamp          string   `protobuf:"bytes,5,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMessagesRequest) Reset()         { *m = ReadMessagesRequest{} }
func (m *ReadMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMessagesRequest) ProtoMessage()    {}
func (*ReadMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{14}
}
func (m *ReadMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMessagesRequest.Unmarshal(m, b)
}
func (m *ReadMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *ReadMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMessagesRequest.Merge(dst, src)
}
func (m *ReadMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_ReadMessagesRequest.Size(m)
}
func (m *ReadMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMessagesRequest proto.InternalMessageInfo

func (m *ReadMessagesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ReadMessagesRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReadMessagesRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *ReadMessagesRequest) GetFromTimestamp() string {
	if m != nil {
		return m.FromTimestamp
	}
	return ""
}

func (m *ReadMessagesRequest) GetToTimestamp() string {
	if m != nil {
		return m.ToTimestamp
	}
	return ""
}

type ReadMessagesResponse struct {
	Messages             []*ReadMessagesResponse_Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ReadMessagesResponse) Reset()         { *m = ReadMessagesResponse{} }
func (m *ReadMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMessagesResponse) ProtoMessage()    {}
func (*ReadMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{15}
}
func (m *ReadMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMessagesResponse.Unmarshal(m, b)
}
func (m *ReadMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMessagesResponse.Marshal(b, m, deterministic)
}
func (dst *ReadMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMessagesResponse.Merge(dst, src)
}
func (m *ReadMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_ReadMessagesResponse.Size(m)
}
func (m *ReadMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMessagesResponse proto.InternalMessageInfo

func (m *ReadMessagesResponse) GetMessages() []*ReadMessagesResponse_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type ReadMessagesResponse_Message struct {
	// RFC3339 UTC
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMessagesResponse_Message) Reset()         { *m = ReadMessagesResponse_Message{} }
func (m *ReadMessagesResponse_Message) String() string { return proto.CompactTextString(m) }
func (*ReadMessagesResponse_Message) ProtoMessage()    {}
func (*ReadMessagesResponse_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{15, 0}
}
func (m *ReadMessagesResponse_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMessagesResponse_Message.Unmarshal(m, b)
}
func (m *ReadMessagesResponse_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMessagesResponse_Message.Marshal(b, m, deterministic)
}
func (dst *ReadMessagesResponse_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMessagesResponse_Message.Merge(dst, src)
}
func (m *ReadMessagesResponse_Message) XXX_Size() int {
	return xxx_messageInfo_ReadMessagesResponse_Message.Size(m)
}
func (m *ReadMessagesResponse_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMessagesResponse_Message.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMessagesResponse_Message proto.InternalMessageInfo

func (m *ReadMessagesResponse_Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ReadMessagesResponse_Message) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ReadMessagesResponse_Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetConversationsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationsRequest) Reset()         { *m = GetConversationsRequest{} }
func (m *GetConversationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetConversationsRequest) ProtoMessage()    {}
func (*GetConversationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{16}
}
func (m *GetConversationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationsRequest.Unmarshal(m, b)
}
func (m *GetConversationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetConversationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationsRequest.Merge(dst, src)
}
func (m *GetConversationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetConversationsRequest.Size(m)
}
func (m *GetConversationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationsRequest proto.InternalMessageInfo

func (m *GetConversationsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetConversationsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetConversationsResponse struct {
	Somethings           []*GetConversationsResponse_Conversation `protobuf:"bytes,1,rep,name=somethings,proto3" json:"somethings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *GetConversationsResponse) Reset()         { *m = GetConversationsResponse{} }
func (m *GetConversationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetConversationsResponse) ProtoMessage()    {}
func (*GetConversationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{17}
}
func (m *GetConversationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationsResponse.Unmarshal(m, b)
}
func (m *GetConversationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetConversationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationsResponse.Merge(dst, src)
}
func (m *GetConversationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetConversationsResponse.Size(m)
}
func (m *GetConversationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationsResponse proto.InternalMessageInfo

func (m *GetConversationsResponse) GetSomethings() []*GetConversationsResponse_Conversation {
	if m != nil {
		return m.Somethings
	}
	return nil
}

type GetConversationsResponse_Conversation struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationName     string   `protobuf:"bytes,2,opt,name=conversation_name,json=conversationName,proto3" json:"conversation_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationsResponse_Conversation) Reset()         { *m = GetConversationsResponse_Conversation{} }
func (m *GetConversationsResponse_Conversation) String() string { return proto.CompactTextString(m) }
func (*GetConversationsResponse_Conversation) ProtoMessage()    {}
func (*GetConversationsResponse_Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_0423117cd19a1cf1, []int{17, 0}
}
func (m *GetConversationsResponse_Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationsResponse_Conversation.Unmarshal(m, b)
}
func (m *GetConversationsResponse_Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationsResponse_Conversation.Marshal(b, m, deterministic)
}
func (dst *GetConversationsResponse_Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationsResponse_Conversation.Merge(dst, src)
}
func (m *GetConversationsResponse_Conversation) XXX_Size() int {
	return xxx_messageInfo_GetConversationsResponse_Conversation.Size(m)
}
func (m *GetConversationsResponse_Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationsResponse_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationsResponse_Conversation proto.InternalMessageInfo

func (m *GetConversationsResponse_Conversation) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *GetConversationsResponse_Conversation) GetConversationName() string {
	if m != nil {
		return m.ConversationName
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "protos.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protos.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "protos.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "protos.RegisterResponse")
	proto.RegisterType((*IsAuthenticatedRequest)(nil), "protos.IsAuthenticatedRequest")
	proto.RegisterType((*IsAuthenticatedResponse)(nil), "protos.IsAuthenticatedResponse")
	proto.RegisterType((*CreateConversationRequest)(nil), "protos.CreateConversationRequest")
	proto.RegisterType((*CreateConversationResponse)(nil), "protos.CreateConversationResponse")
	proto.RegisterType((*JoinConversationRequest)(nil), "protos.JoinConversationRequest")
	proto.RegisterType((*JoinConversationResponse)(nil), "protos.JoinConversationResponse")
	proto.RegisterType((*IsConversationMemberRequest)(nil), "protos.IsConversationMemberRequest")
	proto.RegisterType((*IsConversationMemberResponse)(nil), "protos.IsConversationMemberResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "protos.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "protos.SendMessageResponse")
	proto.RegisterType((*ReadMessagesRequest)(nil), "protos.ReadMessagesRequest")
	proto.RegisterType((*ReadMessagesResponse)(nil), "protos.ReadMessagesResponse")
	proto.RegisterType((*ReadMessagesResponse_Message)(nil), "protos.ReadMessagesResponse.Message")
	proto.RegisterType((*GetConversationsRequest)(nil), "protos.GetConversationsRequest")
	proto.RegisterType((*GetConversationsResponse)(nil), "protos.GetConversationsResponse")
	proto.RegisterType((*GetConversationsResponse_Conversation)(nil), "protos.GetConversationsResponse.Conversation")
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor_exchange_0423117cd19a1cf1) }

var fileDescriptor_exchange_0423117cd19a1cf1 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0x94, 0x13, 0x9a, 0x9f, 0x69, 0x92, 0x16, 0xb7, 0x34, 0x26, 0xed, 0xa1, 0xac, 0x8a, 0xa8,
	0x54, 0xe1, 0x03, 0x48, 0x1c, 0xf9, 0x51, 0x85, 0x4a, 0x10, 0xe1, 0x60, 0x38, 0x71, 0xa9, 0xb6,
	0xf1, 0x87, 0x63, 0x21, 0xef, 0xa6, 0xde, 0x0d, 0xf0, 0x04, 0x3c, 0x11, 0x12, 0x8f, 0xc1, 0x2b,
	0xa1, 0xd8, 0xeb, 0x78, 0xad, 0xb8, 0x52, 0x41, 0xe4, 0x14, 0xed, 0xec, 0xec, 0xcc, 0x64, 0x76,
	0xf3, 0x05, 0x03, 0xfa, 0x3e, 0x9d, 0x71, 0x11, 0x91, 0x3f, 0x4f, 0xa5, 0x96, 0x6e, 0x2b, 0xfb,
	0x50, 0xec, 0x0c, 0xbd, 0x77, 0x32, 0x8a, 0x45, 0x40, 0xd7, 0x0b, 0x52, 0xda, 0x3d, 0x44, 0x77,
	0xa1, 0x28, 0xbd, 0x14, 0x3c, 0x21, 0xcf, 0x39, 0x76, 0x4e, 0xbb, 0x41, 0x67, 0x09, 0xbc, 0xe7,
	0x09, 0xb1, 0xe7, 0xe8, 0x1b, 0xb2, 0x9a, 0x4b, 0xa1, 0xc8, 0xdd, 0xc7, 0x96, 0x96, 0x5f, 0x48,
	0x18, 0x66, 0xbe, 0x70, 0x87, 0x68, 0x67, 0x1a, 0x71, 0xe8, 0x35, 0x32, 0xbc, 0xb5, 0x5c, 0x8e,
	0x43, 0xe6, 0x63, 0x27, 0xa0, 0x28, 0x56, 0x9a, 0xd2, 0x5b, 0xf9, 0xb9, 0xd8, 0x2d, 0xf9, 0xb9,
	0x25, 0xbb, 0xc0, 0xc1, 0x58, 0xbd, 0x5a, 0xe8, 0x19, 0x09, 0x1d, 0x4f, 0xb9, 0xa6, 0xb0, 0x90,
	0xfa, 0xcb, 0x30, 0x2f, 0x30, 0x5c, 0x13, 0x32, 0x5f, 0xeb, 0x04, 0x7d, 0x6e, 0x6f, 0x64, 0x8a,
	0x9d, 0xa0, 0x0a, 0xb2, 0x6f, 0xb8, 0x7f, 0x9e, 0x12, 0xd7, 0x74, 0x2e, 0xc5, 0x57, 0x4a, 0x15,
	0xd7, 0xb1, 0x5c, 0xf5, 0x68, 0xd9, 0x3a, 0xb6, 0x6d, 0x99, 0xb2, 0x61, 0xa7, 0x3c, 0xc3, 0xdd,
	0xa9, 0xa5, 0x92, 0xd7, 0xd1, 0xcc, 0x18, 0xbb, 0xf6, 0x46, 0x56, 0xcb, 0x6b, 0x8c, 0xea, 0x8c,
	0x4d, 0xf8, 0x47, 0xd8, 0xa9, 0x48, 0xad, 0x12, 0x0c, 0x6c, 0x78, 0x1c, 0xb2, 0x6b, 0x0c, 0xdf,
	0xca, 0x58, 0xfc, 0x87, 0xf4, 0x35, 0x96, 0xcd, 0x5a, 0xcb, 0x11, 0xbc, 0x75, 0x4b, 0x73, 0xb1,
	0x0b, 0x1c, 0x8e, 0x95, 0xbd, 0x33, 0xa1, 0xe4, 0xaa, 0x7c, 0x28, 0x9b, 0x8a, 0xf4, 0x0c, 0x47,
	0xf5, 0xb6, 0xa6, 0xce, 0x03, 0xb4, 0x92, 0x0c, 0x31, 0x8f, 0xc0, 0xac, 0xd8, 0x0f, 0x07, 0xee,
	0x07, 0x12, 0xe1, 0x84, 0x94, 0xe2, 0x11, 0x6d, 0x38, 0xa6, 0xeb, 0xa1, 0x3d, 0x95, 0x42, 0x93,
	0xd0, 0xde, 0x9d, 0x8c, 0x50, 0x2c, 0xd9, 0x3d, 0xec, 0x55, 0x72, 0x98, 0x3a, 0x7f, 0x39, 0xd8,
	0x0b, 0x88, 0x17, 0xb8, 0xda, 0x74, 0xc0, 0x87, 0x18, 0x7c, 0x4e, 0x65, 0x72, 0xa9, 0xe3, 0x84,
	0x94, 0xe6, 0xc9, 0xdc, 0xe4, 0xec, 0x2f, 0xd1, 0x8f, 0x05, 0xe8, 0x3e, 0x40, 0x4f, 0x4b, 0x8b,
	0xb4, 0x95, 0x91, 0xb6, 0xb5, 0x5c, 0x51, 0xd8, 0x4f, 0x07, 0xfb, 0xd5, 0xe4, 0xe6, 0x2a, 0x5e,
	0xa2, 0x93, 0x18, 0xcc, 0x73, 0x8e, 0x9b, 0xa7, 0xdb, 0x4f, 0x4e, 0xf2, 0x69, 0xa6, 0xfc, 0x3a,
	0xbe, 0x5f, 0x54, 0xb2, 0x3a, 0x35, 0xfa, 0x84, 0xb6, 0x01, 0xdd, 0x23, 0x74, 0xcb, 0x14, 0x79,
	0x13, 0x25, 0x70, 0xe3, 0xd4, 0xb0, 0xef, 0xa1, 0x59, 0xbd, 0x87, 0x37, 0x18, 0x5e, 0x90, 0xb6,
	0x5f, 0xd2, 0x3f, 0x76, 0xce, 0x7e, 0x3b, 0xf0, 0xd6, 0xa5, 0x4c, 0x09, 0x13, 0x40, 0xc9, 0x84,
	0xf4, 0x2c, 0x16, 0x51, 0x51, 0xc3, 0xe3, 0xa2, 0x86, 0x9b, 0x4e, 0xf9, 0x95, 0x5f, 0x9c, 0x25,
	0x30, 0x0a, 0xd1, 0xb3, 0xf7, 0x6e, 0x3d, 0x3d, 0xea, 0x27, 0x56, 0xa3, 0x7e, 0x62, 0x5d, 0xe5,
	0xff, 0x36, 0x4f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x37, 0x84, 0x99, 0x86, 0x06, 0x00,
	0x00,
}
