// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

package function

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{3}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type IsAuthenticatedRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthenticatedRequest) Reset()         { *m = IsAuthenticatedRequest{} }
func (m *IsAuthenticatedRequest) String() string { return proto.CompactTextString(m) }
func (*IsAuthenticatedRequest) ProtoMessage()    {}
func (*IsAuthenticatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{4}
}
func (m *IsAuthenticatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthenticatedRequest.Unmarshal(m, b)
}
func (m *IsAuthenticatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthenticatedRequest.Marshal(b, m, deterministic)
}
func (dst *IsAuthenticatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthenticatedRequest.Merge(dst, src)
}
func (m *IsAuthenticatedRequest) XXX_Size() int {
	return xxx_messageInfo_IsAuthenticatedRequest.Size(m)
}
func (m *IsAuthenticatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthenticatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthenticatedRequest proto.InternalMessageInfo

func (m *IsAuthenticatedRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IsAuthenticatedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type IsAuthenticatedResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthenticatedResponse) Reset()         { *m = IsAuthenticatedResponse{} }
func (m *IsAuthenticatedResponse) String() string { return proto.CompactTextString(m) }
func (*IsAuthenticatedResponse) ProtoMessage()    {}
func (*IsAuthenticatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{5}
}
func (m *IsAuthenticatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthenticatedResponse.Unmarshal(m, b)
}
func (m *IsAuthenticatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthenticatedResponse.Marshal(b, m, deterministic)
}
func (dst *IsAuthenticatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthenticatedResponse.Merge(dst, src)
}
func (m *IsAuthenticatedResponse) XXX_Size() int {
	return xxx_messageInfo_IsAuthenticatedResponse.Size(m)
}
func (m *IsAuthenticatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthenticatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthenticatedResponse proto.InternalMessageInfo

func (m *IsAuthenticatedResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

type CreateConversationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationName     string   `protobuf:"bytes,3,opt,name=conversation_name,json=conversationName,proto3" json:"conversation_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationRequest) Reset()         { *m = CreateConversationRequest{} }
func (m *CreateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConversationRequest) ProtoMessage()    {}
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{6}
}
func (m *CreateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationRequest.Unmarshal(m, b)
}
func (m *CreateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationRequest.Merge(dst, src)
}
func (m *CreateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConversationRequest.Size(m)
}
func (m *CreateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationRequest proto.InternalMessageInfo

func (m *CreateConversationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateConversationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateConversationRequest) GetConversationName() string {
	if m != nil {
		return m.ConversationName
	}
	return ""
}

type CreateConversationResponse struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationResponse) Reset()         { *m = CreateConversationResponse{} }
func (m *CreateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResponse) ProtoMessage()    {}
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{7}
}
func (m *CreateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResponse.Unmarshal(m, b)
}
func (m *CreateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResponse.Marshal(b, m, deterministic)
}
func (dst *CreateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResponse.Merge(dst, src)
}
func (m *CreateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResponse.Size(m)
}
func (m *CreateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResponse proto.InternalMessageInfo

func (m *CreateConversationResponse) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type JoinConversationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationId       string   `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinConversationRequest) Reset()         { *m = JoinConversationRequest{} }
func (m *JoinConversationRequest) String() string { return proto.CompactTextString(m) }
func (*JoinConversationRequest) ProtoMessage()    {}
func (*JoinConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{8}
}
func (m *JoinConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinConversationRequest.Unmarshal(m, b)
}
func (m *JoinConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinConversationRequest.Marshal(b, m, deterministic)
}
func (dst *JoinConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinConversationRequest.Merge(dst, src)
}
func (m *JoinConversationRequest) XXX_Size() int {
	return xxx_messageInfo_JoinConversationRequest.Size(m)
}
func (m *JoinConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinConversationRequest proto.InternalMessageInfo

func (m *JoinConversationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *JoinConversationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinConversationRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type JoinConversationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinConversationResponse) Reset()         { *m = JoinConversationResponse{} }
func (m *JoinConversationResponse) String() string { return proto.CompactTextString(m) }
func (*JoinConversationResponse) ProtoMessage()    {}
func (*JoinConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{9}
}
func (m *JoinConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinConversationResponse.Unmarshal(m, b)
}
func (m *JoinConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinConversationResponse.Marshal(b, m, deterministic)
}
func (dst *JoinConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinConversationResponse.Merge(dst, src)
}
func (m *JoinConversationResponse) XXX_Size() int {
	return xxx_messageInfo_JoinConversationResponse.Size(m)
}
func (m *JoinConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinConversationResponse proto.InternalMessageInfo

type SendMessageRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConversationId       string   `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{10}
}
func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (dst *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(dst, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SendMessageRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SendMessageRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *SendMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_f661088bb534080c, []int{11}
}
func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (dst *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(dst, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "protos.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protos.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "protos.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "protos.RegisterResponse")
	proto.RegisterType((*IsAuthenticatedRequest)(nil), "protos.IsAuthenticatedRequest")
	proto.RegisterType((*IsAuthenticatedResponse)(nil), "protos.IsAuthenticatedResponse")
	proto.RegisterType((*CreateConversationRequest)(nil), "protos.CreateConversationRequest")
	proto.RegisterType((*CreateConversationResponse)(nil), "protos.CreateConversationResponse")
	proto.RegisterType((*JoinConversationRequest)(nil), "protos.JoinConversationRequest")
	proto.RegisterType((*JoinConversationResponse)(nil), "protos.JoinConversationResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "protos.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "protos.SendMessageResponse")
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor_exchange_f661088bb534080c) }

var fileDescriptor_exchange_f661088bb534080c = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x49, 0xfb, 0xff, 0xf7, 0xe3, 0x62, 0x3f, 0x1c, 0x3f, 0x1a, 0xeb, 0x46, 0x06, 0x41,
	0xa1, 0xd0, 0x8d, 0x7b, 0x45, 0x8a, 0x48, 0x44, 0x5d, 0xc4, 0x07, 0x90, 0x31, 0xb9, 0xa4, 0x83,
	0x74, 0xa6, 0xcd, 0xdc, 0xa8, 0x4f, 0xe0, 0x73, 0x4b, 0x27, 0x69, 0x3b, 0xa1, 0x59, 0x28, 0xe8,
	0x2a, 0xdc, 0x73, 0x0f, 0xe7, 0xfc, 0x72, 0x43, 0xa0, 0x8b, 0x1f, 0xd1, 0x54, 0xa8, 0x04, 0xc7,
	0xf3, 0x54, 0x93, 0x66, 0x0d, 0xfb, 0x30, 0x7c, 0x04, 0x3b, 0xf7, 0x3a, 0x91, 0x2a, 0xc4, 0x45,
	0x86, 0x86, 0xd8, 0x31, 0xb4, 0x33, 0x83, 0xe9, 0xb3, 0x12, 0x33, 0xf4, 0xbd, 0x13, 0xef, 0xbc,
	0x1d, 0xb6, 0x96, 0xc2, 0xa3, 0x98, 0x21, 0xbf, 0x84, 0x4e, 0x61, 0x36, 0x73, 0xad, 0x0c, 0xb2,
	0x7d, 0xf8, 0x4f, 0xfa, 0x15, 0x55, 0xe1, 0xcc, 0x07, 0x36, 0x80, 0xa6, 0xcd, 0x90, 0xb1, 0x5f,
	0xb3, 0x7a, 0x63, 0x39, 0x06, 0x31, 0x1f, 0x43, 0x2f, 0xc4, 0x44, 0x1a, 0xc2, 0xf4, 0x5b, 0x7d,
	0x0c, 0xfa, 0x1b, 0x7f, 0x5e, 0xc9, 0x6f, 0xe1, 0x30, 0x30, 0xd7, 0x19, 0x4d, 0x51, 0x91, 0x8c,
	0x04, 0x61, 0xbc, 0x8a, 0xfa, 0x21, 0xcc, 0x15, 0x0c, 0xb6, 0x82, 0x8a, 0xd7, 0x3a, 0x85, 0x8e,
	0x70, 0x17, 0x36, 0xb1, 0x15, 0x96, 0x45, 0xfe, 0x0e, 0x47, 0x93, 0x14, 0x05, 0xe1, 0x44, 0xab,
	0x37, 0x4c, 0x8d, 0x20, 0xa9, 0xd7, 0x77, 0x74, 0x6a, 0x3d, 0xb7, 0x76, 0x43, 0x59, 0x73, 0x29,
	0x47, 0xb0, 0x1b, 0x39, 0x29, 0xf9, 0x39, 0xea, 0xd6, 0xd1, 0x77, 0x17, 0xf6, 0x2c, 0x37, 0x30,
	0xac, 0x2a, 0x2e, 0xe0, 0xcf, 0xa0, 0x57, 0x8a, 0x5a, 0x13, 0x74, 0x5d, 0x39, 0x88, 0xf9, 0x02,
	0x06, 0x77, 0x5a, 0xaa, 0x5f, 0xa0, 0xaf, 0xa8, 0xac, 0x57, 0x56, 0x0e, 0xc1, 0xdf, 0xae, 0x2c,
	0x3e, 0xec, 0xa7, 0x07, 0xec, 0x09, 0x55, 0xfc, 0x80, 0xc6, 0x88, 0x04, 0xff, 0x18, 0x85, 0xf9,
	0xd0, 0x8c, 0xb4, 0x22, 0x54, 0xe4, 0xff, 0xb3, 0x86, 0xd5, 0xc8, 0x0f, 0x60, 0xaf, 0xc4, 0x91,
	0xf3, 0xbd, 0xe4, 0x7f, 0xcc, 0xc5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xaf, 0xc4, 0x59,
	0x4a, 0x03, 0x00, 0x00,
}
