// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

package function

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_a159d36ef6342b32, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_a159d36ef6342b32, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_a159d36ef6342b32, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_a159d36ef6342b32, []int{3}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type IsAuthenticatedRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthenticatedRequest) Reset()         { *m = IsAuthenticatedRequest{} }
func (m *IsAuthenticatedRequest) String() string { return proto.CompactTextString(m) }
func (*IsAuthenticatedRequest) ProtoMessage()    {}
func (*IsAuthenticatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_a159d36ef6342b32, []int{4}
}
func (m *IsAuthenticatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthenticatedRequest.Unmarshal(m, b)
}
func (m *IsAuthenticatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthenticatedRequest.Marshal(b, m, deterministic)
}
func (dst *IsAuthenticatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthenticatedRequest.Merge(dst, src)
}
func (m *IsAuthenticatedRequest) XXX_Size() int {
	return xxx_messageInfo_IsAuthenticatedRequest.Size(m)
}
func (m *IsAuthenticatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthenticatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthenticatedRequest proto.InternalMessageInfo

func (m *IsAuthenticatedRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IsAuthenticatedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type IsAuthenticatedResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthenticatedResponse) Reset()         { *m = IsAuthenticatedResponse{} }
func (m *IsAuthenticatedResponse) String() string { return proto.CompactTextString(m) }
func (*IsAuthenticatedResponse) ProtoMessage()    {}
func (*IsAuthenticatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_a159d36ef6342b32, []int{5}
}
func (m *IsAuthenticatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthenticatedResponse.Unmarshal(m, b)
}
func (m *IsAuthenticatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthenticatedResponse.Marshal(b, m, deterministic)
}
func (dst *IsAuthenticatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthenticatedResponse.Merge(dst, src)
}
func (m *IsAuthenticatedResponse) XXX_Size() int {
	return xxx_messageInfo_IsAuthenticatedResponse.Size(m)
}
func (m *IsAuthenticatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthenticatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthenticatedResponse proto.InternalMessageInfo

func (m *IsAuthenticatedResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "protos.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protos.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "protos.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "protos.RegisterResponse")
	proto.RegisterType((*IsAuthenticatedRequest)(nil), "protos.IsAuthenticatedRequest")
	proto.RegisterType((*IsAuthenticatedResponse)(nil), "protos.IsAuthenticatedResponse")
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor_exchange_a159d36ef6342b32) }

var fileDescriptor_exchange_a159d36ef6342b32 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xad, 0x48, 0xce,
	0x48, 0xcc, 0x4b, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a,
	0xda, 0x5c, 0x3c, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0xd2, 0x5c, 0x9c, 0xa5, 0xc5, 0xa9, 0x45, 0xf1, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x1c, 0x20, 0x01, 0xbf, 0xc4, 0xdc, 0x54, 0x25, 0x3b, 0x2e, 0x5e, 0xa8, 0xe2,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0xa8,
	0x4a, 0x08, 0x47, 0x48, 0x9c, 0x8b, 0x1d, 0x6c, 0x46, 0x66, 0x8a, 0x04, 0x13, 0x58, 0x9c, 0x0d,
	0xc4, 0xf5, 0x4c, 0x51, 0xd2, 0xe3, 0xe2, 0x0f, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0x22,
	0xca, 0x3e, 0x21, 0x2e, 0x01, 0x84, 0x7a, 0x88, 0x95, 0x4a, 0xee, 0x5c, 0x62, 0x9e, 0xc5, 0x8e,
	0xa5, 0x25, 0x19, 0xa9, 0x79, 0x25, 0x99, 0xc9, 0x89, 0x25, 0xa9, 0x29, 0x30, 0xa3, 0x48, 0x74,
	0x8c, 0x3d, 0x97, 0x38, 0x86, 0x41, 0x50, 0x6f, 0xa9, 0x70, 0xf1, 0x26, 0x22, 0x4b, 0x80, 0x4d,
	0xe4, 0x08, 0x42, 0x15, 0x4c, 0x82, 0x04, 0xa1, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xbe,
	0x00, 0xc1, 0x5b, 0x01, 0x00, 0x00,
}
